apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: airtasker-prod

resources:
  - ../../base
  - namespace.yaml
 
images:
  - name: airtasker-task
    newName: airtasker-task
    newTag: v1.0.0
