apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod- 
resources:
  - ../../../base 
  
images:
  - name: airtasker-task
    newName: usarvesh/airtasker
    newTag: latest

patches:
  - path: ingress-weighted-patch.yaml
    target: 
      kind: Ingress 