apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airtasker-task-monitor
  namespace: monitoring   
  labels:
    release: prometheus-stack  
spec:
  selector:
    matchLabels:
      name: airtasker-task
  namespaceSelector:
    matchNames: 
      - airtasker-prod
  endpoints:
    - port: http   
      path: /metrics
      interval: 5s
